spring:
  application:
    name: CONFIGURATION-SERVICE
  data:
    mongodb:
      authentication-database: admin
      username: root
      password: root
      database: configuration
      port: 27017
      host: localhost
    redis:
      host: localhost
      port: 6379
      password: eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
  cache:
    type: redis
server:
  port: 0
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:password@localhost:8777/eureka/
logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate: DEBUG